name: Build & Release
on:
  push:
    branches:
      - rel

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    needs: release
    if: always()

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mcdreforged

      - name: Pack
        id: pack
        run: |
          mcdreforged pack --ignore-patterns __pycache__ -i ${{ needs.release.outputs.path }}
          echo "name=$(ls *.mcdr)" >> $GITHUB_OUTPUT

      - name: Upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ needs.release.outputs.tag_name }} ${{ steps.pack.outputs.name }}

  release:
    runs-on: ubuntu-latest
    name: AutoRelease

    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs[format('{0}--tag_name', steps.get-path.outputs.path)] }}
      path: ${{ steps.get-path.outputs.path }}

    steps:
      - name: Init release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release/.release-config.json
          manifest-file: .release/.release-manifest.json

      - name: Get Path
        id: get-path
        if: always()
        run: |
          echo "path=${{ fromJson(steps.release.outputs.paths_released)[0] }}" >> $GITHUB_OUTPUT